sonar.projectKey=gocart
sonar.projectName=GoCart
sonar.projectVersion=1.0

sonar.sources=.

sonar.sourceEncoding=UTF-8

#sonar.host.url=http://localhost:9000
#sonar.token=sqp_75674a54ac9e2379082950117901c3ccb2d3033d

# Exclude folders
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.git/**

# JavaScript / React
sonar.javascript.lcov.reportPaths=coverage/lcov.info
